QuizOnlineDeveloper/QuizOnlineDeveloper/Controllers/BankController.cs
using Model.Dao;
using Model.EF;
using Model.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Common;

namespace QuizOnlineDeveloper.Controllers
{
    public class BankController : BaseController
    {
        // GET: Bank
        [Authorize(Roles = "Admin, User")]
        public ActionResult Index()
        {
            using (DBCONTENT db = new DBCONTENT())
            {
                var sess = (UserLogin)Session[new CommonConstant().USER_SESSION];
                var listbank = (from x in db.Categories
                                join o in db.User_Categories
                                on x.CategoryID equals o.CategoryID
                                where o.UserID == sess.UserID
                                select x
                                ).ToList();
                var list = CategoryRequest.GenTreeView(listbank);
                var test = new ExamDao().getTypeName(sess.UserID);
                ViewBag.quizTest = test;
                return View(list);
            }

        }
        [Authorize(Roles = "Admin, User")]
        //Get List Question From Category
        public JsonResult Question(string typename)
        {
            var sess = (UserLogin)Session[new CommonConstant().USER_SESSION];
            var ques = new QuestionDAO().GetAllQuestionOnCatelory(typename,sess.UserID);
            return Json(ques, JsonRequestBehavior.AllowGet);
        }
        //Get Question From Category
        [Authorize(Roles = "Admin, User")]
        public JsonResult GetQuestion(long quesID)
        {
            var question = new QuestionDAO().GetQuestion(quesID);
            return Json(question, JsonRequestBehavior.AllowGet);
        }

        //Tạo bank
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Createbank()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Createbank(string TopicName, string[] BankArrr)
        {
            var sess = (UserLogin)Session[new CommonConstant().USER_SESSION];
            var listcate = new CategoryDao().getCategoryname(sess.UserID);
            ViewBag.listcate = listcate;
            int check = listcate.IndexOf(TopicName);
            if (check != -1)
            {
                SetAlert("Tạo bank thất bại", "error");
                return Json(sess, JsonRequestBehavior.AllowGet);
            }
            if (TopicName != null && check == -1)
            {
                long? ParentID = null;
                ParentID = new CategoryDao().insertCategory(ParentID, TopicName);
                new CategoryDao().insertCategoryUser((long)ParentID, sess.UserID);
                if (BankArrr == null) return View();
                else
                {
                    for (int i = 0; i < BankArrr.Length; i++)
                    {
                        if (BankArrr[i] != null)
                        {
                            var categoryid = new CategoryDao().insertCategory(ParentID, BankArrr[i]);
                            new CategoryDao().insertCategoryUser(categoryid, sess.UserID);
                        }
                    }
                    SetAlert("Tạo bank thành công", "success");
                    return Json(sess, JsonRequestBehavior.AllowGet);
                }
            }
            else return View();
        }
        
        //chỉnh sửa câu hỏi trong bank
        [Authorize(Roles = "Admin, User")]
        public ActionResult Edit(long questionID, string questioncontent, int dokho, long hocphan, 
            string[] answercontent, string[] Istrue, string image)
        {
            var sess = (UserLogin)Session[new CommonConstant().USER_SESSION];
            bool check = new QuestionDAO().EditQuestion(sess.UserID, questionID, questioncontent,
                dokho, hocphan, answercontent, Istrue, image);
            return View();
        }
    }
}

QuizOnlineDeveloper/QuizOnlineDeveloper/Controllers/CalendarController.cs
using Microsoft.AspNet.SignalR.Messaging;
using Model.Common;
using Model.Dao;
using Model.EF;
using Model.ModelCustom;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizOnlineDeveloper.Controllers
{
    public class CalendarController : BaseController
    {
        // GET: Calendar
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetCalendarData()
        {


            using (DBCONTENT db = new DBCONTENT())
            {
                var sess = (UserLogin)Session[new CommonConstant().USER_SESSION];
                var classID = new ClassDao().GetClassIDByUserID(sess.UserID);
                List<long> temp = new List<long>();
                List<long> examID = new List<long>();
                for (int i = 0; i < classID.Length; i++)
                {
                    temp = new ExamDao().GetExamIDByClassID(classID[i]);
                    if (temp.Count != 0)
                        examID.AddRange(temp);
                }
                examID = (List<long>)examID.Distinct().ToList();

                List<CalendarExamCustom> data = new List<CalendarExamCustom>();
                for (int i = 0; i < examID.Count; i++)
                {
                    var myExamID = examID[i];
                    var obj = db.Exams.Where(m => m.ExamID == myExamID).Select(m => new CalendarExamCustom
                    {
                        Title = m.ExamName,
                        Start_Date = (DateTime)m.StartDay,
                        End_Date = (DateTime)m.EndDay
                    }).FirstOrDefault();
                    if (obj != null)
                        data.Add(obj);
                }

                return Json(data, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

QuizOnlineDeveloper/QuizOnlineDeveloper/Controllers/ContactController.cs
using CommonProject;
using Model.ModelCustom;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizOnlineDeveloper.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        [HttpGet]
        public ActionResult ContactUS()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ContactUS(ContactToAdmin model)
        {
            if (ModelState.IsValid)
            {
                sendEmailContacttoAdmin(model);
                ViewBag.Success = "Cảm ơn Bạn đã phản hồi cho chúng tôi! Chúng tôi sẽ sớm liên hệ lại cho bạn !";
                ModelState.Clear();
                ViewBag.Section = "contact";
                return View();
            }
            else
            {
                ViewBag.Error = "error";
            }
            ViewBag.Section = "contact";
            return View(model);
        }
        public void sendEmailContacttoAdmin(ContactToAdmin message)
        {
            string content = System.IO.File.ReadAllText(Server.MapPath("~/Asserts/Client/template/ContactAdmin.html"));
            content = content.Replace("{{Day}}", DateTime.Now.ToString("dd/MM/yyyy hh:mm"));
            content = content.Replace("{{Subject}}", message.Subject);
            content = content.Replace("{{Name}}", message.Name);
            content = content.Replace("{{Mail}}", message.Email);
            content = content.Replace("{{Content}}", message.Content);
            var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();
            new MailHelper().SendMail(toEmail, "Report", content, "Phản hồi của người dùng");
        }
    }
}

QuizOnlineDeveloper/QuizOnlineDeveloper/Controllers/ExamController.cs
using Model.Common;
using Model.Dao;
using Model.EF;
using Model.ModelCustom;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizOnlineDeveloper.Controllers
{
    public class ExamController : BaseController
    {
        // GET: Exam
        [Authorize(Roles = "Admin, User")]
        [ActionName("List")]
        [HttpGet]
        public ActionResult Index()
        {
            var listExams = new ExamDao().GetAllExams();
            return View(listExams);
        }


        [Authorize(Roles = "Admin, User")]
        public ActionResult Details(long examID)
        {
            using (DBCONTENT db = new DBCONTENT())
            {
                var exam = db.Exams.Where(m => m.ExamID == examID).FirstOrDefault();
                return PartialView("Details", exam);
            }
        }


        
        [Authorize(Roles = "Admin, User")]
        [HttpPost]
        //[ActionName("CheckCode")]
        public ActionResult CheckCode(string examCode, long examID)
        {
            using (DBCONTENT db = new DBCONTENT())
            {
                var session = (UserLogin)Session[new CommonConstant().USER_SESSION];
                var userID = session.UserID;
                var check = new ExamDao().CheckExam(examID, examCode, userID);


                var classExam = new ExamDao().GetClassExamID(userID, examID);
                var exam = new ExamDao().GetExamByID(examID);
                var modelExam = new ExamCustom();
                if (check)
                {
                    //return Json(check, JsonRequestBehavior.AllowGet);
                    modelExam = new ExamCustom
                    {
                        ClassExamID = classExam.ClassExamID,
                        ExamID = exam.ExamID,
                        QuantityQuestion = (int)exam.QuantityQuestion,
                        QuantityEasyQues = (int)exam.EasyQuestion,
                        QuantityMediumQues = (int)exam.NormalQuestion,
                        QuantityHardQues = (int)exam.HardQuestion,
                        ExamCategoryID = exam.ExamCategoryID,
                        UserID = userID
                    };
                    TempData["modelExam"] = modelExam;
                    //TRuyền qua xong nói t team view chạy. Miễn ren ở Action Attemp nhận dc TempData là dc
                    return Json(modelExam, JsonRequestBehavior.AllowGet);
                }
                return View();
            }
        }
    }
}

QuizOnlineDeveloper/QuizOnlineDeveloper/Views/Shared/ContactUs.cshtml
@model Model.ModelCustom.ContactToAdmin
<section class="contact-block">
    <div class="contact-form">
        <div class="section-title">
            <h2>Liên hệ với chúng tôi</h2>
        </div>
        <div class="form-filde" id="Y">
            @using (Html.BeginForm("ContactUs", "Contact", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                if (ViewBag.Success != null)
                {
                    <div class="alert alert-success alert-dismissible fade in">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Thành công!</strong>
                        <div class="input-box">
                            <p class="">@ViewBag.Success</p>
                        </div>
                    </div>
                }
                if (ViewBag.Error != null)
                {
                    <div class="alert alert-warning alert-dismissible fade in" id="alertError">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Lỗi!</strong>
                        <div class="input-box">
                            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                        </div>
                    </div>
                }
                <div class="input-box">
                    @Html.TextBoxFor(model => model.Name, new { @placeholder = "Họ & Tên" })
                </div>
                <div class="input-box">
                    @Html.TextBoxFor(model => model.Email, new { @placeholder = "Địa chỉ mail của bạn" })
                </div>
                <div class="input-box">
                    @Html.TextBoxFor(model => model.Subject, new { @placeholder = "Tiêu đề" })
                </div>
                <div class="input-box">
                    @Html.TextAreaFor(model => model.Content, new { @placeholder = "Tin nhắn", @rows = "2" })
                </div>
                <div class="submit-slide" style="text-align: center !important;">
                    <input type="submit" value="Gửi Mail" class="btn">
                </div>

            }
        </div>
    </div>
    <div class="map-responsive map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3834.594359723897!2d108.24099841538234!3d16.03461814462248!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3142175ea5d8d99d%3A0x2e7e2969e5e69555!2zMTQgRG_Do24gVeG6qW4sIEtodcOqIE3hu7ksIE5nxakgSMOgbmggU8ahbiwgxJDDoCBO4bq1bmcsIFZp4buHdCBOYW0!5e0!3m2!1svi!2s!4v1596101014216!5m2!1svi!2s"
                width="100%" height="650" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</section>

QuizOnlineDeveloper/QuizOnlineDeveloper/Views/Shared/Menu.cshtml
<header id="header">
    <div class="container">
        <nav id="nav-main">
            <div class="navbar navbar-inverse">
                <div class="navbar-header">
                    <a href="/trang-chu" class="navbar-brand"><img src="~/Asserts/Client/images/logo.png" alt=""></a>
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                @*<div class="cart-box">
                    <a href="cart.html"><i class="fa fa-shopping-basket"></i></a>
                </div>*@
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active sub-menu">
                            @Html.ActionLink("Trang Chủ", "Index", "Home")

                        </li>
                        <li class="mega-menu sub-menu">
                            <a href="#">Khóa học</a>
                            <div class="menu-view">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <ul>
                                            <li>
                                                @Html.ActionLink("Tạo mới khóa học", "Create", "CreateClass")
                                            </li>
                                            <li>
                                                @Html.ActionLink("Khóa học tham gia", "MyClass", "ClassManagerment")
                                            </li>
                                            <li>
                                                @Html.ActionLink("Khóa học của tôi", "Index", "ClassManagerment")
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="sub-menu mega-menu">
                            <a href="#">Topic</a>
                            <div class="menu-view" style="left: 66% !important">
                                <div class="row">
                                    <div class="col-sm-12 ">
                                        <ul>
                                            <li>
                                                @Html.ActionLink("Tạo topic", "Createbank", "Bank")
                                            </li>
                                            <li>
                                                @Html.ActionLink("Tạo câu hỏi", "Create", "Questions")
                                            </li>
                                            <li>
                                                @Html.ActionLink("Import file excel", "List", "Questions")
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <li class="sub-menu mega-menu">
                            <a href="#">Kiểm tra</a>
                            <div class="menu-view" style="left: 66% !important">
                                <div class="row">
                                    <div class="col-sm-12 ">
                                        <ul>
                                            <li>
                                                @Html.ActionLink("Tạo bài kiểm tra", "Create", "CreateQuiz")
                                            </li>
                                            <li>
                                                @Html.ActionLink("Danh sách kiểm tra", "List", "Exam")
                                            </li>

                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </li>


                        <li>
                            @Html.ActionLink("Liên hệ", "ContactUS", "Contact")
                        </li>
                        <li class="mega-menu sub-menu">
                            @{
                                var sess = (Model.Common.UserLogin)Session[new Model.Common.CommonConstant().USER_SESSION];
                            }
                            @if (sess == null)
                            {
                                <a href="javascript:void(0);"><i class="far fa-smile"></i></a>
                            }
                            else
                            {
                                <a><i class="fas fa-bars"></i></a>
                                <div class="menu-view" style="left: 80% !important">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <ul>
                                                <li>
                                                    @Html.ActionLink("Thông tin cá nhân", "Index", "UpdateUser")
                                                </li>
                                                <li>
                                                    @Html.ActionLink("Lịch của tôi", "Index", "Calendar")
                                                </li>
                                                <li>
                                                    @Html.ActionLink("Ngân hàng của tôi", "Index", "Bank")
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</header>

QuizOnlineDeveloper/QuizOnlineDeveloper/Views/Shared/Slidebar.cshtml
<section class="banner">
    <div class="banner-img"><img src="~/Asserts/Client/images/banner/banner-img1.jpg" alt=""></div>
    <div class="banner-text">
        <div class="container">
            <h1>Tham gia vào lớp</h1>
            <p>Nhập Code để tham gia lớp học và làm kiểm tra</p>
            <div class="search-box">
                <input type="text" placeholder="Nhập mã code">
                <input type="submit" value="">
            </div>
            <div class="learning-btn">
                @Html.ActionLink("Tham gia lớp", "Index", "ClassManagerment ", new { @class = "btn" })
            </div>
        </div>
    </div>
</section>

QuizOnlineDeveloper/QuizOnlineDeveloper/Views/Shared/_Header.cshtml
<div class="quck-nav">
    <div class="container">
        <div class="contact-no">
            <a href="#">
                <i class="fa fa-map-marker"></i>Tòa Nhà FPT Complex, Đường Nam Kỳ
                Khởi Nghĩa, Phường Hoà Hải, Quận Ngũ Hành Sơn, TP Đà Nẵng
            </a>
        </div>
        <div class="contact-no"><a href="#"><i class="fa fa-phone"></i>0984 888 888</a></div>
        <!-- <div class="contact-no"><a href="#"><i class="fa fa-globe"></i>academy.com</a></div> -->
        <div class="quck-right">
            <div class="right-link language-select">
                @{
                    var sess = (Model.Common.UserLogin)Session[new Model.Common.CommonConstant().USER_SESSION];
                }
                @if( sess == null){
                <a href="javascript:void(0);"><i class="fa fa-language"></i>Xin chào bạn</a>

                }
                else{
                <a href="javascript:void(0);"><i class="fa fa-language"></i>Xin chào: @sess.UserName</a>
                }
                @*<ul class="language-list">
            <li><a href="#">Tiếng Anh</a></li>
        </ul>*@
            </div>
            <div class="right-link">
                @if (sess == null)
                {
                    @Html.ActionLink("Đăng nhập", "Index", "Login") 

                    @Html.ActionLink("Đăng Kí", "Index", "Register",null, new { Style = "margin-left:10px" })

                }
                else
                {
                    @Html.ActionLink("Đăng xuất", "Logout", "Login")
                }


            </div>
        </div>
    </div>
</div>

QuizOnlineDeveloper/QuizOnlineDeveloper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>Trang Chủ</title>
    <link rel="shortcut icon" href="~/Asserts/Client/images/Favicon.ico">
    <link href="~/Asserts/Client/css/bootstrap.css" rel="stylesheet"><!-- bootstrap css -->
    <link href="~/Asserts/Client/css/owl.carousel.css" rel="stylesheet"><!-- carousel Slider -->
    <link href="~/Asserts/Client/css/font-awesome.css" rel="stylesheet"><!-- font awesome -->
    <link href="~/Asserts/Client/css/docs.css" rel="stylesheet"><!--  template structure css -->
    <link href="https://fonts.googleapis.com/css?family=Arima+Madurai:100,200,300,400,500,700,800,900%7CPT+Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i"
          rel="stylesheet">
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <script src="~/Asserts/Client/js/plugins/ckfinder/ckfinder.js"></script>
    <script src="~/Asserts/Client/js/plugins/ckeditor/ckeditor.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
</head>
<body>

    <div class="wapper">
        <div id="loader-wrapper">
            <div id="loader"></div>
            <div class="loader-section section-left"></div>
            <div class="loader-section section-right"></div>
        </div>
        @RenderPage("_Header.cshtml")
        @RenderPage("Menu.cshtml")
        @RenderSection("Slidebar", required: false)

        @RenderBody()
        @RenderSection("ContactUs", required: false)
        @RenderPage("footer.cshtml")
    </div>
    @if (ViewBag.Section != null)
    {
        <script>
            var elmnt = document.getElementById("@ViewBag.Section");
            elmnt.scrollIntoView();

        </script>
    }
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script>
        $(function () {
            var counter = $.connection.counter;
            $.connection.hub.start().done(function () {
               
            })
            counter.client.UpdateCount = function (count) {
            }

        })
    </script>
    @RenderSection("jsFooter", required: false)

</body>


</html>

QuizOnlineDeveloper/QuizOnlineDeveloper/Views/Shared/footer.cshtml
<footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3">
                    <h5>Kiểm Tra Thử</h5>
                    <div class="course-slide">
                        <div class="img"><img src="~/Asserts/Client/images/blog/post-img1.jpg" alt=""></div>
                        <p><a href="courses-list.html">Tiếng Anh </a></p>
                        <div class="price">Miễn Phí</div>
                    </div>
                    <div class="course-slide">
                        <div class="img"><img src="~/Asserts/Client/images/blog/post-img2.jpg" alt=""></div>
                        <p><a href="courses-list-sideBar.html">Toán học </a></p>
                        <div class="price">Miễn Phí</div>
                    </div>
                    <div class="course-slide">
                        <div class="img"><img src="~/Asserts/Client/images/blog/post-img3.jpg" alt=""></div>
                        <p><a href="courses-list.html">Toán IQ</a></p>
                        <div class="price">Miễn Phí</div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="row">
                        <div class="col-md-offset-1 col-sm-6 col-md-5 col-xs-6">
                            <h5>Về chúng tôi</h5>
                            <ul class="footer-link">
                                <li><a href="about-us.html">Điều khoản dịch vụ</a></li>
                                <li><a href="contact-us.html">Điều khoản quảng cáo</a></li>
                                <li><a href="blog.html">Blog</a></li>
                            </ul>
                        </div>
                        <div class="col-md-offset-1 col-sm-6 col-md-5 col-xs-6">
                            <h5>Tính năng</h5>
                            <ul class="footer-link">
                                <li><a href="courses-list.html">Tạo Quiz</a></li>
                                <li><a href="price-plan.html">Giới Thiệu</a></li>
                                <li><a href="forums.html">Lớp học</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <h5>Liên hệ</h5>
                    <div class="contact-view">
                        <div class="contact-slide">
                            <p>
                                <i class="fa fa-location-arrow"></i>14 Doãn Uẩn, Ngũ Hành Sơn<br>Thành phố Đà
                                Nẵng
                            </p>
                        </div>
                        <div class="contact-slide">
                            <p><i class="fa fa-phone"></i>(+84) 984 888 888</p>
                        </div>
                        <div class="contact-slide">
                            <p><i class="fa fa-fax"></i>(+84) 984 999 999</p>
                        </div>
                        <div class="contact-slide">
                            <p>
                                <i class="fa fa-envelope"></i><a href="mailTo:academy@info.com">quizonline@gmail.com</a>
                            </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                <div class="copy-right">
                    <p>Copyright © <span class="year">2020</span> Universal Team</p>
                    <ul class="footer-link">
                        <li><a href="#" style="margin-left:33px;">Chủ nhiệm lớp: Ngô Khánh Ly</a></li>
                    </ul>

                </div>
            </div>
            <div class="col-sm-7">
                <ul class="Support">
                    <li>Người Hướng Dẫn : &nbsp;</li>
                    <li>Đặng Minh Thành --</li>
                    <li>Hồ Đức Lĩnh --</li>
                    <li>Nguyễn Phan Tùng Lâm --</li>
                    <li>Đoàn Ngọc Đạt</li>
                </ul>
            </div>
        </div>
    </div>
    <style>
        .Support {
            margin-top: 20px;
            user-select: none;
        }

            .Support ul {
                list-style-type: none;
                text-align: center;
            }

            .Support li {
                color: #cecece;
                display: inline-block;
            }
    </style>
</footer>