QuizOnlineDeveloper/QuizOnlineDeveloper/Controllers/QuestionsController.cs
using Model.Common;
using Model.Dao;
using Model.EF;
using Model.Services;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizOnlineDeveloper.Controllers
{
    public class QuestionsController : BaseController
    {
        // GET: Questions

        [Authorize(Roles = "Admin, User")]
        public ActionResult Index()
        {
            return View();
        }


        [Authorize(Roles = "Admin, User")]
        [HttpGet]
        public ActionResult Create()
        {
            var session = (UserLogin)Session[new CommonConstant().USER_SESSION];
            // get ID to get Category ID
            var categoryList = new ExamDao().getTypeName(session.UserID);
            ViewBag.categoryList = categoryList;
            return View();
        }



        [Authorize(Roles = "Admin, User")]
        //[ValidateInput(false)]
        [HttpPost]
        //public ActionResult Create(Question[] answerArray)
        public ActionResult Create(Dictionary<string, object>[] answerArray, string editor_data,
            string finder_data, long category_id, int level_question)
        {
            //get userID from Sesstion
            var session = (UserLogin)Session[new CommonConstant().USER_SESSION];
            //intinitial object
            var obj = new QuestionDAO();

            //check redunant question content
            var serviceQuestion = new CheckQuestion();
            var listExistQuestion = new QuestionDAO().GetQuestionContentByUserID(session.UserID);
            if (!serviceQuestion.CheckRedunantQuestion(editor_data, listExistQuestion))
            {
                //check type of questions
                var type = new QuestionDAO().CheckQuestionType(answerArray);
                if (type == 0 || type == 1)
                {
                    // add new question => return QuestionID
                    var questionID = obj.AddQuestion(category_id, session.UserID,
                        level_question, editor_data, finder_data, DateTime.Now, type);
                    long answer;
                    if (questionID > 0 && answerArray.Length > 0)
                    {
                        for (int i = 0; i < answerArray.Length; i++)
                        {
                            answer = obj.AddAnswer(questionID, answerArray[i]["answer"].ToString(), (bool)answerArray[i]["isChecked"]);
                            //var tf = answerArray[i]["answer"];
                            //var tf1 = answerArray[i]["isChecked"];
                        }
                        SetAlert("Thêm câu hỏi thành công!", "success");
                        return Json(questionID, JsonRequestBehavior.AllowGet);
                    }
                }
            }

            SetAlert("Câu hỏi trùng!", "error");
            //return View();
            return Json(session, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Admin, User")]
        public ActionResult List()
        {
            SetAlert("Vui lòng kéo thả file excel vào ô bên dưới!", "warning");
            return View();
        }


        [Authorize(Roles = "Admin, User")]
        [HttpPost]
        public ActionResult List(HttpPostedFileBase excelfile)
        {
            string path = Server.MapPath("~/Data/ExcelFiles");
            string filePath = string.Empty;
            string extension = string.Empty;
            DataTable dtSheet = new DataTable();
            DataSet ExcelData = new DataSet();
            if (excelfile != null)
            {
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                filePath = path + Path.GetFileName(excelfile.FileName);
                extension = Path.GetExtension(excelfile.FileName);
                excelfile.SaveAs(filePath);
            }
            string connectionString = string.Empty;
            switch (extension)
            {
                case ".xls":  // for excel 97-03
                    connectionString = ConfigurationManager.ConnectionStrings["Excel03ConString"].ConnectionString;
                    break;
                case ".xlsx":  // for excel 97-03
                    connectionString = ConfigurationManager.ConnectionStrings["Excel07ConString"].ConnectionString;
                    break;
            }
            connectionString = string.Format(connectionString, filePath);
            using (OleDbConnection connExcel = new OleDbConnection(connectionString))
            {
                using (OleDbCommand cmdExcel = new OleDbCommand())
                {
                    using (OleDbDataAdapter oadExcel = new OleDbDataAdapter())
                    {
                        cmdExcel.Connection = connExcel;
                        //Get the name of firstsheet
                        connExcel.Open();
                        DataTable dtExcelShcema;
                        dtExcelShcema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                        string sheetName = dtExcelShcema.Rows[0]["TABLE_NAME"].ToString();
                        connExcel.Close();

                        //read data from first sheet
                        connExcel.Open();
                        cmdExcel.CommandText = "SELECT * FROM [" + sheetName + "]";
                        oadExcel.SelectCommand = cmdExcel;
                        oadExcel.Fill(dtSheet);
                        connExcel.Close();
                    }
                }
            }
            ExcelData.Tables.Add(dtSheet);
            return View(ExcelData);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Insert(string[][] data)
        //public ActionResult Insert(Dictionary<string, object>[] data)
        {
            var obj = new QuestionDAO();
            //get userID from Sesstion
            var session = (UserLogin)Session[new CommonConstant().USER_SESSION];

            long questionID;
            for (int i = 0; i < data.Length; i++)
            {
                var type = new QuestionDAO().CheckQuesTionTypeByExcel(data[i]);
                var serviceQuestion = new CheckQuestion();
                var listExistQuestion = new QuestionDAO().GetQuestionContentByUserID(session.UserID);
                if (!serviceQuestion.CheckRedunantQuestion(data[i][2], listExistQuestion))
                {
                    // add new question => return QuestionID
                    questionID = obj.AddQuestion(Convert.ToInt64(data[i][0]), session.UserID,
                       Convert.ToInt32(data[i][1]), data[i][2], data[i][3], DateTime.Now, type);

                    for (int j = 4; j < data[i].Length; j = j + 2)
                    {
                        var answer = obj.AddAnswer(questionID, data[i][j], Convert.ToBoolean(Convert.ToInt32(data[i][j + 1])));
                    }
                }
            }
            SetAlert("Thêm câu hỏi thành công!", "success");
            return Json(session, JsonRequestBehavior.AllowGet);

            //return View();
        }

        [Authorize(Roles = "Admin, User")]
        public ActionResult Test()
        {
            return View();
        }
    }
}

QuizOnlineDeveloper/QuizOnlineDeveloper/Views/Questions/Create.cshtml
@model Model.EF.Question

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<link href="~/Asserts/Client/css/MakeQuestions.css" rel="stylesheet" />*@
<link href="~/Asserts/Client/css/dropdown-menu-dashboard-user.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" rel="stylesheet" />


<section class="banner inner-page">
    <div class="banner-img"><img src="~/Asserts/Client/images/banner/quiz.jpg" alt=""></div>
    <div class="page-title">
        <div class="container">
            <h1>Tạo câu hỏi</h1>
        </div>
    </div>
</section>
<section class="breadcrumb white-bg">
    <div class="container">
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="#">Quiz</a></li>
            <li><a href="#">Make Quiz</a></li>
        </ul>
    </div>
</section>
<section class="quiz-view">

    <form action="">
        <div class="container">

            @*<div class="quiz-title">
                    <h1 class=" text-center">Tạo câu hỏi</h>
                </div>*@
            <div class="form-group">
                <!-- div start row -->
                <div class="row">
                    <div class="col-lg-3">
                        <div class="row">

                            <div class="dropdown">
                                <div class="dropdown_select ">
                                    <span class="dropdown_selected a">Type</span>
                                    <i class="fas fa-caret-down"></i>
                                </div>
                                <div class="dropdown_list">
                                    <li class="dropdown_item NormalQuestion">
                                        <span class="dropdown_text">Normal</span>
                                        <i class="fas fa-text-width"></i>
                                    </li>
                                    <li class="dropdown_item IMGQuestion">
                                        <span class="dropdown_text ">Ảnh</span>
                                        <i class="fas fa-images"></i>
                                    </li>
                                    <li class="dropdown_item MediaQuestion">
                                        <span class="dropdown_text ">Media</span>
                                        <i class="fas fa-photo-video"></i>
                                    </li>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="col-lg-9">

                        <div class="col-lg-12 ">
                            @if (TempData["AlertMessage"] != null)
                            {
                                <div id="AlertBox" class="alert @TempData["AlertType"] showAlert">
                                    @TempData["AlertMessage"]
                                    Bạn muốn <a href="/Bank/Index" class="alert-link">xem danh sách vừa tạo </a>hay quay về <a href="/Home/Index" class="alert-link">Trang chủ</a>
                                </div>
                            }
                            <div class="showAlert row"></div>
                            <div class="col-lg-2">
                                <h4>Thư Mục</h4>
                            </div>
                            <div class="col-lg-10">

                                @Html.DropDownListFor(model => model.CategoryID, new SelectList(ViewBag.categoryList, "CategoryID", "Typename", "UserID"), "Please select", new { @class = "form-control categoryclass", id = "dllCategory" })
                            </div>
                        </div>

                        <div class="col-lg-12 ">
                            <div class="col-lg-2">
                                <h4>Chọn Ảnh</h4>
                            </div>
                            <div class="col-lg-10 bothinputbtn">
                                <input class="form-control inputImg" type="text" id="txtImage">
                                <span><button type="submit" class=" btn-default buttonAddImg" id="btnSelectImage">Thêm Ảnh</button></span>
                            </div>
                        </div>

                        <div class="col-lg-12 ">
                            <div class="col-lg-2">
                                <h4>Mức Độ</h4>
                            </div>
                            <div class="col-lg-10">
                                <select class="form-control TypeHardQuestion" id="level-option">
                                    <option value="0">Dễ</option>
                                    <option value="1">Trung bình</option>
                                    <option value="2">Khó</option>
                                </select>
                            </div>
                        </div>

                        <div class="col-lg-12 ">
                            <div class="col-lg-2">
                                <h4>Nội Dung</h4>
                            </div>
                            <div class="col-lg-10">
                                @*<textarea rows="" cols="" class="form-control"></textarea>*@
                                @Html.TextAreaFor(model => model.QuestionContent, new { htmlAttributes = new { @class = "form-control" }, id = "txtContent" })
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="col-lg-2">
                                <h4>Trả lời</h4>
                            </div>
                            <table id="my-table">
                                <div class="col-lg-10 AllAnswer">
                                    <div class="Answer">
                                        <input type="text" class="form-control" name="" id="" placeholder="A.Something">
                                        <small id="helpId" class="form-text text-muted">
                                            Câu trả lời đúng ? 
                                            <input type="checkbox" name="NormalCheck" id="CheckRight" value="checkedValue">
                                        </small>
                                    </div>
                                    <br>
                                    <div class="Answer">
                                        <input type="text" class="form-control" name="" id="" placeholder="B.Something">
                                        <small id="helpId" class="form-text text-muted">
                                            Câu trả lời đúng ?
                                            <input type="checkbox" name="NormalCheck" id="CheckRight" value="checkedValue">
                                        </small>
                                    </div>

                                </div>
                                <div class=" col-lg-12 bothButton">
                                    <div class="col-lg-4">
                                        <a name="" id="AddQuestion" class="btn btn-primary" href="#" role="button">Thêm Answer</a>
                                    </div>
                                    <div class="col-lg-4">
                                        <a name="" id="save" class="btn btn-danger" href="#" role="button">Thêm Question</a>
                                    </div>
                                </div>
                            </table>
                        </div>


                    </div>


                </div>
            </div>
            <!--Div end row -->
        </div>
    </form>
</section>
<link href="~/Asserts/Client/css/CreateQuestionByHand.css" rel="stylesheet" />
<style>
    .bothButton {
        margin: 5% 0px 0px 30%;
    }

    .banner-img img, inner-page {
        height: 350px;
    }

    .dropdown {
        margin-top: 0% !important;
        margin-left: 5rem;
    }

    .showAlert {
        margin-left: 15rem;
    }
</style>
@section jsFooter{

    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>*@
    @*<script src="~/Asserts/Client/js/MakeQuestions.js"></script>*@
    <script>

        $(document).ready(function () {

            setTimeout(function () {
                $('#AlertBox').hide('slow');
            }, 5000);


            // enabled CKFindner
            $('#btnSelectImage').on('click', function (e) {
                e.preventDefault();
                var finder = new CKFinder();
                finder.selectActionFunction = function (url) {
                    $('#txtImage').val(url)
                };
                finder.popup();
            })

            //----------------------------------
            // eanable CKeditor
            var editor = CKEDITOR.replace('txtContent', {
                customConfig: '/Asserts/Client/js/plugins/ckeditor/config.js',
                htmlEncodeOutput: true
            })

            $('#AddQuestion').click(function (e) {
                e.preventDefault();
                $('.AllAnswer').append('<div class="AnswerBonus Answer"><input type="text" class="form-control" name="" id=""><small id="helpId" class="form-text text-muted">Câu trả lời đúng ? <input type="checkbox" name="NormalCheck" id="CheckRight" value="checkedValue"></small></div>');
                $('.AnswerBonus input').blur(function (e) {
                    if ($(this).val() == '') {
                        $(this).parent('.AnswerBonus').remove();
                    }
                });
            });
            //----------------------------------
            // handle button Save pass data to controller
            $('#save').click(function () {
                var answerArray = [];
                var editor_data = CKEDITOR.instances['txtContent'].getData();
                var finder_data = $('#txtImage').val();
                var category_id = $('#dllCategory').val()
                var level_question = $('#level-option').val()


                $(".Answer").each(function (i) {
                    if ($(this).find('input[type="text"]').val() != "") {
                        answerArray[i] = {
                            answer: $(this).find('input[type="text"]').val(),
                            isChecked: $(this).find('input[type="checkbox"]').prop('checked')
                        }
                        //answerArray[i]['answer'] = $(this).find('input[type="text"]').val();
                        //answerArray[i]['id'] = $(this).find('input[type="checkbox"]:checked').val();
                    }
                });


                //check input type=checkbox : isChecked?
                var count = 0;
                for (var i = 0; i < answerArray.length; i++) {
                    if (answerArray[i]["isChecked"] == true) {
                        count++;
                    }
                }
                if (count == 0) {
                    $('.showAlert').html('<div id="AlertBox" class="alert alert-warning">' + "Vui chọn câu trả lời đúng!" + ' </div>');
                }
                else {
                    $.ajax({
                        type: 'POST',
                        url: '/Questions/Create',
                        data: JSON.stringify({
                            'answerArray': answerArray, 'editor_data': editor_data, 'finder_data': finder_data,
                            'category_id': category_id, 'level_question': level_question
                        }),
                        traditional: true,
                        contentType: 'application/json; charset=utf-8',
                        datatype: 'json',
                        success: function (questionID) {
                            location.reload(true);
                            //$('#AlertBox').delay(3600000).slideUp(1000);
                        },
                        error: function () {
                            //location.reload(true);
                            //$('#AlertBox').delay(3600000).slideUp(1000);
                            alert('Failed ');
                        }
                    });
                }
            })
        })
    </script>
}

QuizOnlineDeveloper/QuizOnlineDeveloper/Views/Questions/List.cshtml
@using System.Data
@model DataSet

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Asserts/Client/css/ListQuestionExcel.css" rel="stylesheet" />

<style>

    .banner-img img, inner-page {
        height: 350px;
    }

    #btn-import {
        margin-top: 1%;
    }

    .input-file input[type="file"] {
        display: none;
    }

</style>
<section class="banner inner-page">
    <div class="banner-img"><img src="~/Asserts/Client/images/banner/quiz.jpg" alt=""></div>
    <div class="page-title">
        <div class="container">
            <h1>Import Excel</h1>
        </div>
    </div>
</section>
<section class="breadcrumb white-bg">
    <div class="container">
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="#">Create Questions</a></li>
            <li><a href="#">Excel File</a></li>
        </ul>
    </div>
</section>
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                @if (TempData["AlertMessage"] != null)
                {
                    <div id="AlertBox" class="alert @TempData["AlertType"]">
                        @TempData["AlertMessage"]
                        Quay về <a href="/ngan-hang-cua-toi" class="alert-link">Trang chủ</a>
                    </div>
                }
            </div>
        </div>

        @using (Html.BeginForm("List", "Questions", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.Raw(ViewBag.Error)
            <!--<span>Excel file</span>-->
            @*<input type="file" name="excelfile" />*@
            <!--<div class="input-file">
                <input type="file" name="excelfile" id="file" />
                <label for="file" class="input-label">
                    <i class="fas fa-cloud-upload-alt icon-upload"></i>
                </label>
            </div>
            <br />
            <input type="submit" value="Import" class="btn btn-outline-info" />-->
            <br>
            <div class="row wapper">
                <div class="col-lg-4">
                    <div class="dropdown">
                        <div class="dropdown_select top">
                            <span class="dropdown_selected">
                                Import from desktop
                            </span>
                            <i class="fas fa-cloud-upload-alt"></i>
                        </div>
                        <div class="dropdown_select bottom">
                            <span class="dropdown_selected">
                                Import online
                            </span>
                            <i class="fas fa-upload"></i>
                        </div>

                    </div>
                </div>
                <div class="col-lg-8 ">
                    <div class="input-file">
                        <input type="file" name="excelfile" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" id="file" />
                        <label for="file" class="input-label">
                            <i class="fas fa-cloud-upload-alt icon-upload"></i>

                            <h2 id="selected-file-name" style="color:#939ba4;"> Drag and drop your file</h2>

                        </label>
                    </div>

                    <div class="text-center">
                        <!-- <button type="submit" value="Import" class="btn btn-danger">Import</button> -->
                        <input type="submit" value="Import" class="btn btn-danger btn-sm" id="btn-import" />
                    </div>
                </div>
            </div>

            <br>

        }


        <div class="row">
            <div class="col-xs-12 setTable">
                @if (Model != null)
                {
                    <h2 id="title">Ngân hàng câu hỏi</h2>
                    <table class="table table-bordered table-hover dt-responsive myTable" id="my-table">
                        <thead>
                            <tr>
                                @foreach (DataColumn col in Model.Tables[0].Columns)
                                {

                                    <th align="center"> @col.ColumnName</th>
                                }
                            </tr>

                        </thead>
                        <tbody>
                            @foreach (DataRow row in Model.Tables[0].Rows)
                            {
                                <tr>
                                    @foreach (DataColumn col in Model.Tables[0].Columns)
                                    {
                                        <td>
                                            <input type="text" value="@row[col.ColumnName]"
                                                   data-original-title="@row[col.ColumnName]" data-container="body"
                                                   data-toggle="tooltip" data-placement="bottom" style="text-align: center;" />
                                            @*@row[col.ColumnName]*@
                                        </td>
                                    }
                                </tr>
                            }

                        </tbody>
                    </table>
                    <div class="text-center">
                        <!-- <button type="submit" value="Import" class="btn btn-danger">Import</button> -->
                        <button type="submit" class="btn btn-danger" id="btn-them">Save</button>
                    </div>
                }

                <br />
            </div>
        </div>
    </div>
</section>
@section jsFooter{

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="~/Asserts/Client/js/bootstrap.min.js"></script>
    <link href="~/Asserts/Client/css/bootstrap.css" rel="stylesheet" />
    <script>
        $(document).ready(function () {

            //tooltips
            $(function () {
                $("[data-toggle='tooltip']").tooltip();
            });
            //



            // catch on change event for input tooltips
            $('input[type="text"]').on('input',function (e) {            
                    
            });

            var fileName = "";
            //get selected file name
            $('input[type="file"]').change(function (e) {
                fileName = e.target.files[0].name;
                $('#selected-file-name').html(fileName);
            });

            //event hover tr in table
            $('tr').hover(function () {
                $(this).find('input').css("background-color", "rgb(233, 232, 232)");
            }, function () {
                $(this).find('input').css("background-color", "white");
            });



            $('#btn-them').click(function () {
                var data = Array();
                $("tbody tr").each(function (i, v) {
                    data[i] = Array();
                    $(this).children('td').each(function (ii, vv) {
                        if ($(this).find('input[type="text"]').val() != "")
                            data[i][ii] = $(this).find('input[type="text"]').val();
                    });
                })
                console.log(data);
                $.ajax({
                    type: 'POST',
                    url: '/Questions/Insert',
                    data: JSON.stringify({ 'data': data }),
                    traditional: true,
                    contentType: 'application/json; charset=utf-8',
                    datatype: 'json',
                    success: function (session) {
                        //alert('Thêm thành công!');
                        location.reload(true);
                        //$('#AlertBox').addClass("alert-success");
                        $('#AlertBox').delay(30000).slideUp(1000);
                        window.Location.href = "/ngan-hang-cua-toi";
                    },
                    error: function () {
                        alert('Failed ');
                    }
                });

            });
        });

    </script>
}