QuizOnlineDeveloper/QuizOnlineDeveloper/Controllers/RegisterController.cs
using CaptchaMvc.HtmlHelpers;
using CaptchaMvc.Infrastructure;
using CommonProject;
using Model.Common;
using Model.Dao;
using Model.EF;
using Model.ModelCustom;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizOnlineDeveloper.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(RegisterUser model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                if (dao.checkUserName(model.UserName))
                {
                    ModelState.AddModelError("", "Tên đăng nhập đã tồn tại.");
                    ViewBag.Error = "error";
                }
                if (dao.checkEmail(model.Email))
                {
                    ModelState.AddModelError("", "Địa chỉ mail đã đăng kí trên hệ thống.");
                    ViewBag.Error = "error";
                }
                if (!this.IsCaptchaValid(errorText: ""))
                {
                    ModelState.AddModelError("", "Bạn đã nhập sai mã captcha.");
                    ViewBag.Error = "error";
                }
                else
                {
                    var user = new User();
                    user.UserName = model.UserName;
                    user.Password = Encryptor.MD5Hash(model.Password);
                    user.Email = model.Email;
                    user.Online = false;
                    user.CreateAt = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
                    user.LockStatus = false;
                    var result = dao.InsertUser(user);
                    dao.addUserRole(result, 2);

                    if (result > 0)
                    {
                        string code = Guid.NewGuid().ToString();
                        dao.addActiveCode(code, model.UserName);
                        sendEmailRegister(code, model.Email);
                        ViewBag.Success = "Đăng kí thành công. Vui lòng kiểm tra mail để xác nhận tài khoản";
                        ViewBag.Error = null;
                        ModelState.Clear();
                        return View();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Đăng kí không thành công. Địa chỉ mail không tồn tại !");
                        ViewBag.Error = "error";
                    }
                }
            }
            else
            {
                ViewBag.Error = "error";
            }
            return View(model);
        }
        public ActionResult Confirm(string id)
        {
            var dao = new UserDao();
            dao.ValidateEmail(id);
            return View();
        }
        public void sendEmailRegister(string code, string email)
        {
            string content = System.IO.File.ReadAllText(Server.MapPath("~/Asserts/Client/template/ConfirmRegister.html"));
            var url = "https://localhost:44374/" + "Register/Confirm/" + code;
            content = content.Replace("{{url}}", url);
            var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();
            new MailHelper().SendMail(email, "Xác nhận tài khoản tại Academy", content, "Xác nhận tài khoản");
        }
    }
}

QuizOnlineDeveloper/QuizOnlineDeveloper/Views/Register/Confirm.cshtml
@{
    ViewBag.Title = "Xác nhận tài khoản";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Asserts/Client/css/docss.css" rel="stylesheet" />
<section class="banner inner-page">
    <div class="banner-img"><img style="height: 350px !important" src="~/Asserts/Client/images/banner/register-bannerImg.jpg" alt=""></div>
    <div class="page-title">
        <div class="container">
        </div>
    </div>
</section>
<section class="breadcrumb">
    <div class="container">
        <ul>
            <li><a href="/Home/Index">Trang chủ</a></li>
            <li><a href="#">Xác nhận tài khoản</a></li>
        </ul>
    </div>
    <section class="login-view" style="margin-bottom: 2rem !important;">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <img style="height:700px;width:100%;" src="https://wallpaperaccess.com/full/749909.jpg" />
                </div>
                <div class="col-sm-6">

                    <div class="alert alert-success">
                        <strong>Thành công!</strong>
                        <div class="input-box">
                            <p> Cảm ơn bạn đã xác nhận tài khoản. Bây giờ bạn có thể  <a href="/Login/Index">Đăng nhập</a></p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>
</section>
@section jsFooter{
    <script type="text/javascript" src="~/Asserts/Client/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="~/Asserts/Client/js/bootstrap.js"></script>

}

QuizOnlineDeveloper/QuizOnlineDeveloper/Views/Register/Index.cshtml
@model Model.ModelCustom.RegisterUser
@using CaptchaMvc.HtmlHelpers
@{
    ViewBag.Title = "Đăng kí tài khoản";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Asserts/Client/css/docss.css" rel="stylesheet" />
<section class="banner inner-page">
    <div class="banner-img">
        <img style="        height: 350px !important
" src="~/Asserts/Client/images/banner/register-bannerImg.jpg" alt="">
    </div>
    <div class="page-title">
        <div class="container">
        </div>
    </div>
</section>
<section class="breadcrumb">
    <div class="container">
        <ul>
            <li><a href="/Home/Index">Trang chủ</a></li>
            <li><a href="/Register/Index">Đăng Kí</a></li>
        </ul>
    </div>
</section>
@using (Html.BeginForm("Index", "Register", FormMethod.Post, htmlAttributes: new { @enctype = "multipart/form-data", @id = "fromCaptcha" }))
{
    @Html.AntiForgeryToken()
    <section class="login-view" style="margin-bottom: 2rem !important;">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <img style="height:700px;width:100%;" src="https://wallpaperaccess.com/full/749909.jpg" />
                </div>
                <div class="col-sm-6">
                    <div class="section-title">
                        <h2>Đăng kí tài khoản </h2>
                        <p>Đăng kí tài khoản nhanh chóng với chỉ vài thao tác đơn giản!</p>
                    </div>
                    @if (ViewBag.Success != null)
                    {
                        <div class="alert alert-success alert-dismissible fade in">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <strong>Thành công!</strong>
                            <div class="input-box">
                                <p class="">@ViewBag.Success</p>
                            </div>
                        </div>
                    }
                    @if (ViewBag.Error != null)
                    {
                        <div class="alert alert-warning alert-dismissible fade in hide" id="alertError">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <strong>Lỗi!</strong>
                            <div class="input-box">
                                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    }

                    <div class="input-box">
                        @Html.TextBoxFor(model => model.UserName, new { @placeholder = "Tên đăng nhập" })
                    </div>
                    <div class="input-box">
                        @Html.TextBoxFor(model => model.Email, new { @placeholder = "Địa chỉ mail" })
                    </div>
                    <div class="input-box">
                        @Html.PasswordFor(model => model.Password, new { @placeholder = "Mật khẩu" })
                    </div>
                    <div class="input-box">
                        @Html.PasswordFor(model => model.ConfirmPassword, new { @placeholder = "Nhập lại mật khẩu" })
                    </div>
                    <div class="input-box">
                        @Html.Captcha(refreshText: "Thử lại", inputText: "Nhập mã captcha", length: 6, requiredMessageText: "Is required field", addValidationSpan: true)
                    </div>
                    @*<div class="input-box">
                            <input type="password" placeholder="Nhập mã xác nhận">
                        </div>*@
                    <div class=" text-center">
                        <input type="submit" value="Đăng Kí" class="btn btn-danger">
                    </div>
                </div>
            </div>
        </div>
    </section>
}
@section jsFooter{
    <script type="text/javascript" src="~/Asserts/Client/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="~/Asserts/Client/js/bootstrap.js"></script>
    <script>
        $("#alertError").removeClass('hide');
        $("#alertError").delay(7000).slideUp(1000);
    </script>
}